version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=peering_manager
      - POSTGRES_DB=peering_manager
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000 --insecure
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MY_ASN=393713
      - TIME_ZONE=America/New_York
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=peering_manager
      - DATABASE_NAME=peering_manager
    entrypoint: /code/entrypoint.sh
